[build]
  command = "npm run build"
  publish = "dist"                 # <-- This tells Netlify where your frontend lives
  functions = "netlify/functions" # <-- This tells Netlify where your API functions are

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200                     # <-- Important for single-page app routing